solar_prediction/app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class PredictionValues(db.Model):
    __tablename__ = 'prediction_values'
    id = db.Column(db.Integer, primary_key=True)  
    date = db.Column(db.Date, nullable=False, index=True) 
    value = db.Column(db.Float, nullable=False)
    model_id = db.Column(db.Integer, db.ForeignKey('model_json.id'), nullable=False)
    model = db.relationship('ModelJSON', backref=db.backref('predictions', lazy=True, cascade="all, delete-orphan"))

    def __repr__(self):
        return f"<PredictionValues(date={self.date}, value={self.value})>"

class ModelJSON(db.Model):
    __tablename__ = 'model_json'
    id = db.Column(db.Integer, primary_key=True)  
    name = db.Column(db.String(255), nullable=False, unique=True)
    model_type = db.Column(db.Integer, nullable=False) # 1 for daily, 2 for hourly
    data = db.Column(db.JSON, nullable=False)  
    progress = db.Column(db.JSON, nullable=False)  

    def __repr__(self):
        return f"<ModelJSON(id={self.id}, data={self.data})>"

solar_prediction/app/app.py
# app.py
import os
import numpy as np
from werkzeug.middleware.dispatcher import DispatcherMiddleware
from flask import Flask, json, jsonify, request, render_template, url_for, g
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import pandas as pd
from network import NeuralNetwork
from worker import celery_init_app
from views import views
from api import api
from models import db

celery = None

def create_app():
    global celery
    np.seterr(over='raise')
    app = Flask(__name__)
    if not os.path.exists("/data/instance"):
        try:
            os.makedirs("/data/instance")
        except OSError:
            pass
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////data/instance/db.sqlite'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['CELERY_BROKER_URL'] = 'redis://localhost:6379/0'
    app.config['CELERY_RESULT_BACKEND'] = 'redis://localhost:6379/0'
    app.config.from_mapping(
    CELERY=dict(
        broker_url="redis://localhost",
        result_backend="redis://localhost",
        task_ignore_result=True,
    ),
)
    worker = celery_init_app(app)
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(api, url_prefix="/api")
    db.init_app(app)
    with app.app_context():
        db.create_all()

    migrate = Migrate(app, db) 
        
    def custom_url_for(endpoint, **values):
        ingress_path = request.headers.get("X-Ingress-Path", "")
        url = url_for(endpoint, **values)
        if ingress_path and not url.startswith(ingress_path):
            url = f"{ingress_path}{url}"

        return url
    
    app.jinja_env.globals['url_for'] = custom_url_for
    
    return app

if __name__ == '__main__':
    app = create_app()
    
    app.run(host='0.0.0.0', port=5000, debug=True)

solar_prediction/app/server/app.py
# app.py
from flask import Flask, jsonify, request,render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import pandas as pd
from network import NeuralNetwork
from views import views
from models import db

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

app.register_blueprint(views, url_prefix="/")
db.init_app(app)
Migrate(app, db)

# influx_client = InfluxDBClient(
#         host="localhost",
#         port=8086,
#         username="homeassist",
#         password="homeassist",
#         database="homeassistant",
#     )



if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(host='0.0.0.0', port=5000, debug=True)

solar_prediction/app/views.py
from copy import copy, deepcopy
from datetime import datetime, timedelta
import datetime as dt
from flask import Blueprint, abort, redirect, render_template, request, url_for, jsonify, current_app, g
import pandas as pd
from models import *
from daily import predict
from network import NeuralNetwork
from tasks import train_model, cache_daily_predictions
from celery.result import AsyncResult
from influx import get_influx_data

views = Blueprint("views", __name__)

@views.route("/favicon.ico")
def favicon():
    return redirect(url_for("static", filename="favicon.ico", _external=True))

@views.route('/')
def index():
    models = ModelJSON.query.all()
    if not models:
        return render_template("index.html", exists=False)
    else:
        selected_model_id = request.cookies.get("selected_model")
        if selected_model_id:
            model = ModelJSON.query.get(selected_model_id)
        if not selected_model_id or not model:
            model = models[0]
        
    network = NeuralNetwork()
    network.load(model.data)
    
    date_from = datetime.today()
    date_to = datetime.today() + dt.timedelta(days=4)
    
    existing_predictions = PredictionValues.query.filter(db.func.date(PredictionValues.date )>= date_from.date(), db.func.date(PredictionValues.date )<= date_to.date(), PredictionValues.model_id == model.id).all()
    
    if len(existing_predictions) == (date_to - date_from).days + 1:
        predictions = [pred.value for pred in existing_predictions]
        current_app.logger.debug("Using cached predictions")
    else:
        predictions = predict(network, date_from, date_to)
        cache_daily_predictions.delay(dict(zip([(datetime.today() + timedelta(days=i)).strftime("%Y-%m-%d")  for i in range(5)],predictions)), model.id  ) 
        current_app.logger.debug("Using new predictions") 
    
    
    labels = [(datetime.today() + timedelta(days=i)).strftime("%B %d, %Y") for i in range(5)]
    try:
        influx_data = pd.DataFrame(get_influx_data(date_from, date_to).raw["series"][0]["values"], columns=["time", "mean_value"])
        influx_data = influx_data.dropna()
        actual = list(influx_data["mean_value"])
    except:
        actual = []
    return render_template("index.html", exists=True, result=predictions, labels=labels, models=models, selected_model=model, actual=actual)

@views.route('/models')
def models():
    tasks = []

    return render_template("models.html", models=ModelJSON.query.all(), tasks=tasks)
    
@views.route('/settings')
def settings():
    return render_template("settings.html")

solar_prediction/app/templates/base.html
<!DOCTYPE html>
<html lang="en" data-theme="dark">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SolarPrediction</title>
  <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

  <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://unpkg.com/htmx.org@1.7.0"></script>
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  <script src="{{url_for('static', filename='js/base.js')}}"></script>
  {% block header %}

  {% endblock %}

</head>


<body class="bg-base-100">
  <div class=" flex flex-col h-screen justify-between">
    {% block content %}

    {% endblock %}
  </div>
</body>

</html>

solar_prediction/app/templates/footer.html
<footer class="footer bg-base-200 text-base-content p-10 ">
  <aside>
    <svg width="50" height="50" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd"
      clip-rule="evenodd" class="fill-current">
      <path
        d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-</div>1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z">
      </path>
    </svg>
    <p>
      Solar Prediction
      <br />
      
    </p>
  </aside>
  
</footer>

solar_prediction/app/templates/index.html
{% extends 'base.html' %}
{% block header %}

<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/flatpickr.css')}}">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{%endblock%}

{% block content %}

{% include 'navbar.html' %}

{% if exists %}

<!-- Main Content -->
<div class="pt-20 container mx-auto px-4">
  <h1 class="text-4xl font-semibold text-center mt-4 mb-4">Predictions</h1>

  <div
    class="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-2 xl:grid-rows-1 gap-4 border-t border-gray-700 rounded px-2 w-full mx-0 mt-2">
    <div class="container" hidden>
      <h2 class="text-3xl font-semibold text-center mt-3 mb-2">Hourly</h2>
      <div class="dropdown">
        <div tabindex="0" role="button" class="btn m-1">Click</div>
        <ul tabindex="0" class="dropdown-content menu bg-base-100 rounded-box z-[1] w-52 p-2 shadow">
          <li><a>Item 1</a></li>
          <li><a>Item 2</a></li>
        </ul>
      </div>
      <input type="text" id="dateRangePickerHourly" class="input w-full max-w-xs">
      <div class="bg-base-200 rounded-lg shadow p-3 w-auto h-96">
        <canvas id="hourlyChart" class="h-full"></canvas>
      </div>
    </div>
      <div class="container w-full">
        <div class="flex justify-center">
          <div>
            <h2 class="text-3xl font-semibold text-center mt-3 mb-2">Daily</h2>
    
            <div class="dropdown">
              <div tabindex="0" role="button" id="daily-model-dropdown" class="btn m-1"
                data-model-id="{{selected_model.id}}">{{selected_model.name}}</div>
              <ul tabindex="0" class="dropdown-content menu bg-base-100 rounded-box z-[1] w-52 p-2 shadow">
                {%for model in models%}
                <li><a onclick="changeDailyModel('{{model.id}}', '{{model.name}}')">{{model.name}}</a></li>
                {%endfor%}
              </ul>
            </div>
            <input type="text" id="dateRangePickerDaily" class="input w-full max-w-xs">
            <div class="bg-base-200 rounded-lg shadow p-3 w-auto h-96">
              <canvas id="dailyChart" class="h-full"></canvas>
            </div>

          </div>

        </div>
      </div>
    </div>

    <!-- Button to Update Chart Data via HTMX -->
    <div class="flex justify-center mt-6">
      <button class="btn btn-primary"
        onclick="changeDailyModel(document.getElementById('daily-model-dropdown').dataset.modelId, document.getElementById('daily-model-dropdown').textContent)">
        Update Chart Data
      </button>
    </div>
  </div>

  <script>
    // Function to change the daily model and update chart data
    function changeDailyModel(modelId, modelName, cache = false) {
      const dateRange = document.getElementById('dateRangePickerDaily').value;
      let modelBtn = document.getElementById('daily-model-dropdown');
      modelBtn.dataset.modelId = modelId;


      fetch("{{ url_for('api.index_daily_change_date') }}", {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ model_id: modelId, date_range: dateRange, cache: cache ? true : null })
      })
        .then(response => response.json())
        .then(data => {
          dailyChart.data.datasets[0].data = data.predictions;
          dailyChart.data.datasets[1].data = data.actual;
          dailyChart.data.labels = data.labels;
          dailyChart.update();
          if (modelBtn.textContent !== modelName && modelName) { modelBtn.textContent = modelName; }
        })
        .catch(error => console.error('Error:', error));
    }

    // Initialize Flatpickr for date range selection
    let dateRangePickerDaily = flatpickr("#dateRangePickerDaily", {
      mode: "range",
      dateFormat: "Y-m-d",
      minDate: new Date().fp_incr(-30), // -1 month from today
      maxDate: new Date().fp_incr(15),  // +15 days from today
      defaultDate: [new Date(), new Date().fp_incr(4)], // today + 4 days
      disableMobile: true, // disable mobile optimizations
      cache: false // disable caching
    });

    // Event listener for date range change
    dateRangePickerDaily.config.onChange.push(function (selectedDates, dateStr, instance) {
      changeDailyModel(document.getElementById('daily-model-dropdown').dataset.modelId);
    });

    let dateRangePickerHourly = flatpickr("#dateRangePickerHourly", {
      mode: "range",
      dateFormat: "Y-m-d:H",
      defaultDate: [new Date(), new Date().fp_incr(1)], // today + 4 days
      disableMobile: true, // disable mobile optimizations
      cache: false, // disable caching
      enableTime: true, // Enable time selection
      time_24hr: true, // Use 24-hour format
      minDate: new Date().fp_incr(-10), // -10 days from today
      maxDate: new Date().fp_incr(3),  // +3 days from today
    });

    // Event listener for date range change
    dateRangePickerHourly.config.onChange.push(function (selectedDates, dateStr, instance) {
      changeHourlyModel(document.getElementById('hourly-model-dropdown').dataset.modelId);
    });

    // Initialize Chart.js for hourly chart
    const hourlyCtx = document.getElementById('hourlyChart').getContext('2d');
    const hourlyGradient = hourlyCtx.createLinearGradient(0, 0, 0, 400);
    hourlyGradient.addColorStop(0, '#3B82F620');
    hourlyGradient.addColorStop(1, '#3B82F600');

    const hourlyGradient2 = hourlyCtx.createLinearGradient(0, 0, 0, 400);
    hourlyGradient2.addColorStop(0, '#EF444450');
    hourlyGradient2.addColorStop(1, '#EF444400');

    const hourlyChart = new Chart(hourlyCtx, {
      type: 'bar',
      data: {
        labels: [1, 2, 3, 4, 5],
        datasets: [
          {
            type: 'bar',
            label: 'Units Sold',
            data: JSON.parse("{{result}}"),
            backgroundColor: hourlyGradient2,
            borderColor: '#B91C1C',
            borderWidth: 1
          },
          {
            type: 'line',
            label: 'Revenue',
            data: [],
            fill: true,
            backgroundColor: hourlyGradient,
            borderColor: '#3B82F6',
            borderWidth: 2,
            tension: 0.4,
            pointBackgroundColor: '#3B82F6',
            pointBorderColor: '#DBEAFE',
          },
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            position: 'top',
          },
          tooltip: {
            mode: 'index',
            intersect: false,
          },
        },
        scales: {
          x: {
            display: true,
            title: {
              display: true,
              text: 'Month',
              color: '#333',
              font: {
                size: 14,
                weight: 'bold'
              },
            },
            grid: {
              display: true,
              color: 'rgba(255, 255, 255, 0.01)',
            },
          },
          y: {
            display: true,
            title: {
              display: true,
              text: 'Revenue ($)',
              font: {
                size: 14,
                weight: 'bold'
              },
            },
            ticks: {
              beginAtZero: true,
            },
            grid: {
              display: true,
              color: 'rgba(255, 255, 255, 0.01)',
            },
          },
        },
      }
    });

    // Initialize Chart.js for daily chart
    const dailyCtx = document.getElementById('dailyChart').getContext('2d');
    const dailyGradient = dailyCtx.createLinearGradient(0, 0, 0, 400);
    dailyGradient.addColorStop(0, '#3B82F620');
    dailyGradient.addColorStop(1, '#3B82F600');

    const dailyGradient2 = dailyCtx.createLinearGradient(0, 0, 0, 400);
    dailyGradient2.addColorStop(0, '#EF444450');
    dailyGradient2.addColorStop(1, '#EF444400');

    const dailyChart = new Chart(dailyCtx, {
      type: 'bar',
      data: {
        labels: JSON.parse('{{ labels | tojson | safe }}'),
        datasets: [
          {
            type: 'bar',
            label: 'Predict Power (kWh)',
            data: JSON.parse("{{result}}"),
            backgroundColor: dailyGradient2,
            borderColor: '#B91C1C',
            borderWidth: 1
          },
          {
            type: 'line',
            label: 'Actual Power (kWh)',
            data: JSON.parse("{{actual}}"),
            fill: true,
            backgroundColor: dailyGradient,
            borderColor: '#3B82F6',
            borderWidth: 2,
            tension: 0.4,
            pointBackgroundColor: '#3B82F6',
            pointBorderColor: '#DBEAFE',
          },
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            position: 'top',
          },
          tooltip: {
            mode: 'index',
            intersect: false,
          },
        },
        scales: {
          x: {
            display: true,
            title: {
              display: true,
              text: 'Days',
              color: '#333',
              font: {
                size: 14,
                weight: 'bold'
              },
            },
            grid: {
              display: true,
              color: 'rgba(255, 255, 255, 0.01)',
            },
          },
          y: {
            display: true,
            title: {
              display: true,
              text: 'Power (kWh)',
              font: {
                size: 14,
                weight: 'bold'
              },
            },
            ticks: {
              beginAtZero: true,
            },
            grid: {
              display: true,
              color: 'rgba(255, 255, 255, 0.01)',
            },
          },
        },
      }
    });


  </script>
  {% else %}
  <div class="fixed inset-0 flex items-center justify-center bg-base-100">
    <div class="text-center">
      <ion-icon name="alert-circle" class="text-6xl text-red-500 mb-4"></ion-icon>
      <h1 class="text-2xl font-semibold mb-2">You don't have a model</h1>
      <a href="{{ url_for('views.models') }}" class="btn btn-primary">Train Models</a>
    </div>
  </div>
  {% endif %}


  {% include 'footer.html' %}
  {% endblock %}

solar_prediction/app/templates/models.html
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col items-center justify-center h-100 mt-40">
    <div class="bg-base-200 shadow-md rounded-lg p-6 mb-6 w-1/2">
        <h2 class="text-2xl font-bold mb-4">Create New Model</h2>
        <form action="{{ url_for('api.create_model') }}" method="post" class="flex w-full justify-between">
            <div>
                <label for="name" class="block text-sm font-medium text-base-content">Model Name</label>
                <input type="text" name="name" id="name" class="input input-bordered w-full" required>
            </div>
            <div>
                <label for="type" class="block text-sm font-medium text-base-content">Model Type</label>
                <select name="type" id="type" class="select select-bordered w-full" required>
                    <option value="daily">Daily</option>
                    <option value="hourly">Hourly</option>
                </select>
            </div>
            <div class="flex items-center">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
    <div class="bg-base-100 shadow-md rounded-lg p-6 w-100">
        <h2 class="text-2xl font-bold mb-4">Models List</h2>
        <ul class="space-y-2 max-h-30 overflow-y-auto">
            {% for model in models %}
            <li class="p-4 bg-base-200 rounded-lg shadow-sm flex justify-between items-center">
                <div>
                    <h3 class="text-xl font-semibold">{{ model.name }}</h3>
                    <p class="text-gray-600">
                        {% if model.model_type == 1 %}
                        Daily
                        {% elif model.model_type == 1 %}
                        Hourly
                        {% endif %}
                    </p>
                </div>
                <form action="{{ url_for('api.delete_model') }}" method="post">
                    <input type="text" name="model_id" value="{{ model.id }}" hidden>
                    <button type="submit" class="btn btn-error">Delete</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

solar_prediction/app/templates/navbar.html
<nav class="navbar fixed top-0 left-0 right-0 z-50 shadow-md rounded-b-2xl"
    style="backdrop-filter: blur(30px);background-color: #00000010;">
    <div class="container mx-auto px-4 py-3 flex justify-between items-center">
      <a href="{{url_for('views.index')}}" class="text-xl font-bold text-content">Solar Prediction</a>
      <ul class="flex space-x-4">
        <li><a href="{{url_for('views.index')}}" class="text-content ">Predictions</a></li>
        <li><a href="{{url_for('views.models')}}" class="text-content ">Models</a></li>
        <li><a href="{{url_for('views.settings')}}" class="text-content ">Settings</a></li>
      </ul>
    </div>
  </nav>

solar_prediction/app/templates/settings.html
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html'   %}

{% include 'footer.html' %}
{% endblock %}